AWSTemplateFormatVersion: '2010-09-09'
Description: Parent stack calling child stacks

Parameters:
  KeyName:
    Description: "SSH access to the instance"
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: "Must be the name of an existing EC2 KeyPair."

  EnvironmentName:
    Type: String
    Description: Name of the environment (e.g., Dev, Staging, Prod)

  VpcCidr:
    Type: String
    Default: 10.1.0.0/16
    Description: CIDR block for the VPC

  PublicSubnetCidr:
    Type: String
    Default: 10.1.1.0/24
    Description: CIDR block for the Public Subnet

  PrivateSubnetCidr:
    Type: String
    Default: 10.1.2.0/24
    Description: CIDR block for the Private Subnet

Resources:
  # ネットワークスタック
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://myapp-cloudformation-bs.s3.ap-northeast-1.amazonaws.com/Network.yaml"
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VpcCidr: !Ref VpcCidr
        PublicSubnetCidr: !Ref PublicSubnetCidr
        PrivateSubnetCidr: !Ref PrivateSubnetCidr
  
  # アプリケーションスタック
  ApplicationStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://myapp-cloudformation-bs.s3.ap-northeast-1.amazonaws.com/Application.yaml"
      Parameters:
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        PublicSubnetId: !GetAtt NetworkStack.Outputs.PublicSubnetId
        PrivateSubnetId: !GetAtt NetworkStack.Outputs.PrivateSubnetId
        KeyName: !Ref KeyName

Outputs:
  NetworkStackId:
    Description: The Stack ID for the Network Stack
    Value: !Ref NetworkStack

  ApplicationStackId:
    Description: The Stack ID for the Application Stack
    Value: !Ref ApplicationStack